# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - id: kpk
    binary: kpk
    main: .
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
#      - darwin_arm64
#      - windows_amd64
    hooks:
      post:
        - cmd: ./after-build.sh {{ .Path }}
  - id: traceIdHttp
    binary: traceIdHttp
    main: ./traceIdHttp
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
    hooks:
      post:
        - cmd: ./after-build.sh {{ .Path }}
